### ISSUE TITLE
Is it supposed to use fabs rather than abs??

### ISSUE THREAD

**Issue by kagecom** [CMU-Perceptual-Computing-Lab/caffe_train#10]
In src/caffe/cpm_data_transformer.cpp, line 1111, the code shows below:

float dist = std::abs(ba.x*bc.y -ba.y*bc.x);

Is it supposed to use fabs rather than abs??

cuz it it floating number calculation.

**Comment by gineshidalgo99** [comment]
It doesn't matter, does it? (I'm not an expert on floating vs. integer operations, let me know if I am missing something)
http://en.cppreference.com/w/cpp/numeric/math/fabs
https://stackoverflow.com/a/3118188/4054516

**Comment by kagecom** [comment]
it doesn't matter really, std::abs is slightly different from abs
