### ISSUE TITLE
is this a bug in cpm_data_layer.cpp

### ISSUE THREAD

**Issue by trantorrepository** [CMU-Perceptual-Computing-Lab/caffe_train#2]
in function generateLabelMap

  if (np == 56){
    for (int i = 0; i < 18; i++){
      Point2f center = meta.joint_self.joints[i];
      if(meta.joint_self.isVisible[i] <= 1){
        putGaussianMaps(transformed_label + (i+np+39)*channelOffset, center, param_.stride(), 
                        grid_x, grid_y, param_.sigma()); //self
      }
      for(int j = 0; j < meta.numOtherPeople; j++){ //for every other person
        Point2f center = meta.joint_others[j].joints[i];
        if(meta.joint_others[j].isVisible[i] <= 1){
          putGaussianMaps(transformed_label + (i+np+39)*channelOffset, center, param_.stride(), 
                          grid_x, grid_y, param_.sigma());
        }
      }
    }

since np_in_lmdb = 17, 18 is wrong?

**Comment by nnop** [comment]
The answer is no.
